.TH TINYTIMER 6
.SH NAME
tinytimer \- tiny timer with splits for the terminal
.SH SYNOPSIS
.B tinytimer
[\fB\-\-file\fR \fIFILE\fR]
[\fB\-\-log\fR \fILOG\fR]
.SH DESCRIPTION
.B tinytimer
is a little timer for your terminal.
.SH OPTIONS
.TP
.BR \-\-file =\fISPLITS\fR
File to read to get split data from.
Default is splits.txt.
.TP
.BR \-\-log =\fILOG\fR
Log to write to. This parameter is optional,
default is stdout.